// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.charu.roorest.domain;

import com.charu.roorest.domain.UserPK;
import java.io.Serializable;

privileged aspect UserPK_Roo_Serializable {
    
    declare parents: UserPK implements Serializable;
    
    private static final long UserPK.serialVersionUID = 1L;
    
}
