// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.charu.roorest.domain;

import com.charu.roorest.domain.AccountIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AccountIntegrationTest_Roo_Configurable {
    
    declare @type: AccountIntegrationTest: @Configurable;
    
}
