// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.charu.roorest.domain;

import com.charu.roorest.domain.Account;
import com.charu.roorest.domain.AccountDataOnDemand;
import com.charu.roorest.domain.Role;
import com.charu.roorest.domain.RoleDataOnDemand;
import com.charu.roorest.domain.User;
import com.charu.roorest.domain.UserDataOnDemand;
import com.charu.roorest.domain.UserPK;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserDataOnDemand: @Component;
    
    private Random UserDataOnDemand.rnd = new SecureRandom();
    
    private List<User> UserDataOnDemand.data;
    
    @Autowired
    private AccountDataOnDemand UserDataOnDemand.accountDataOnDemand;
    
    @Autowired
    private RoleDataOnDemand UserDataOnDemand.roleDataOnDemand;
    
    public User UserDataOnDemand.getNewTransientUser(int index) {
        User obj = new User();
        setEmbeddedIdClass(obj, index);
        setAccountId(obj, index);
        setEmail(obj, index);
        setName(obj, index);
        setPassword(obj, index);
        setRoleId(obj, index);
        return obj;
    }
    
    public void UserDataOnDemand.setEmbeddedIdClass(User obj, int index) {
        Integer id = new Integer(index);
        Integer roleId = new Integer(index);
        Integer accountId = new Integer(index);
        
        UserPK embeddedIdClass = new UserPK(id, roleId, accountId);
        obj.setId(embeddedIdClass);
    }
    
    public void UserDataOnDemand.setAccountId(User obj, int index) {
        Account accountId = accountDataOnDemand.getRandomAccount();
        obj.setAccountId(accountId);
    }
    
    public void UserDataOnDemand.setEmail(User obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 90) {
            email = new Random().nextInt(10) + email.substring(1, 90);
        }
        obj.setEmail(email);
    }
    
    public void UserDataOnDemand.setName(User obj, int index) {
        String name = "name_" + index;
        if (name.length() > 90) {
            name = name.substring(0, 90);
        }
        obj.setName(name);
    }
    
    public void UserDataOnDemand.setPassword(User obj, int index) {
        String password = "password_" + index;
        if (password.length() > 150) {
            password = password.substring(0, 150);
        }
        obj.setPassword(password);
    }
    
    public void UserDataOnDemand.setRoleId(User obj, int index) {
        Role roleId = roleDataOnDemand.getRandomRole();
        obj.setRoleId(roleId);
    }
    
    public User UserDataOnDemand.getSpecificUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        User obj = data.get(index);
        UserPK id = obj.getId();
        return User.findUser(id);
    }
    
    public User UserDataOnDemand.getRandomUser() {
        init();
        User obj = data.get(rnd.nextInt(data.size()));
        UserPK id = obj.getId();
        return User.findUser(id);
    }
    
    public boolean UserDataOnDemand.modifyUser(User obj) {
        return false;
    }
    
    public void UserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = User.findUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'User' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<User>();
        for (int i = 0; i < 10; i++) {
            User obj = getNewTransientUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
